name:                ICFP2024
version:             0.1.0.0
github:              "githubuser/ICFP2024"
license:             BSD-3-Clause
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2024 Author name here"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/ICFP2024#readme>

dependencies:
- base >= 4.7 && < 5
- containers
- mtl
- transformers
- singletons
- singletons-th
- singletons-base
- lens 
- distributive
- parsec
- tagged
- HTF
- lens

flags:
  wasm:
    description: "target wasm architecture"
    manual: true
    default: false


ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  ICFP2024-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - ICFP2024
  
  WASM:
    main:                Main.hs
    source-dirs:         wasm
    when:
        condition: flag(wasm)
        then:
          ghc-options:
            - -no-hs-main
            - -optl-mexec-model=reactor
            - -optl-Wl,--export=cmain
            - -o Zilly.wasm
        else:
          ghc-options:
            - -threaded
            - -rtsopts
            - -with-rtsopts=-N

    #- -no-hs-main
    #- -optl-mexec-model=reactor
    #- -optl-Wl,--export=cmain
    #- -o Zilly.wasm
    dependencies:
    - ICFP2024

tests:
  ICFP2024-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - ICFP2024
