name: build
run-name: ${{github.actor}} pushed new code to ${{github.repository}}, building...
on:
  push:
    branches:
      - origin
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: haskell-actions/setup
        with:
          enable-stack: true
          stack-setup-ghc: true
      - name: Build the project 
        run: |
          stack build
      